[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c \"python3 ./initialize.py && python3 ./run_ui.py --host 0.0.0.0 --port 80\""
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[variables]
PORT.default = "80"
WEB_UI_PORT.default = "80"