# Railway configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 -u railway_app.py"
healthcheckPath = "/health"
healthcheckTimeout = 200

[environments.production.env]
RAILWAY = "true"
PYTHONUNBUFFERED = "1"
DEBUG = "true"
FLASK_ENV = "production"
FLASK_APP = "railway_app.py"
PORT = "8080"
