# Railway configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 run_ui.py"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[variables]
RAILWAY = "true"
PYTHONUNBUFFERED = "1"
