# Railway configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --worker-class=gevent --workers=2 --threads=4 --timeout=0 --bind=0.0.0.0:$PORT \"run_ui:app\""
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[variables]
RAILWAY = "true"
PYTHONUNBUFFERED = "1"
