# Railway configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 -u railway_app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[environments.production.env]
RAILWAY = "true"
PYTHONUNBUFFERED = "1"
DEBUG = "true"
FLASK_ENV = "production"
FLASK_APP = "railway_app.py"

# Simple configuration for Railway health checks

[variables]
RAILWAY = "true"
PYTHONUNBUFFERED = "1"
