# Simplified Railway configuration for Agent Zero v0.8.4
[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 -u railway_app.py"
healthcheckPath = "/health"
healthcheckTimeout = 60

[environments.production.env]
PYTHONUNBUFFERED = "1"
